---
- name: Deploy Kubernetes Objects
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Delete old deployment
      command: kubectl delete -f /home/ubuntu/kubernetes-project/Deployment.yml
      ignore_errors: yes

    - name: Delete old service
      command: kubectl delete -f /home/ubuntu/kubernetes-project/Service.yml
      ignore_errors: yes

    - name: Create new deployment
      command: kubectl apply -f /home/ubuntu/kubernetes-project/Deployment.yml

    - name: Create new service
      command: kubectl apply -f /home/ubuntu/kubernetes-project/Service.yml
